server:
  port: 8110
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-pay
  swagger:
    title: "pay接口"
    description: "pay接口"
    respackage: com.hmall.pay.controller
