server:
  port: 8100
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-trade
  swagger:
    title: "trade接口"
    description: "trade接口"
    respackage: com.hmall.trade.controller
#spring:
#  rabbitmq:
#    host: 192.168.6.130
#    port: 5672
#    virtual-host: /hmall
#    username: hmall
#    password: 123456
#knife4j:
#  enable: true
#  openapi:
#    title: trade交易接口文档
#    description: "trade交易文档"
#    email: zhanghuyi@itcast.cn
#    concat: 虎哥
#    url: https://www.itcast.cn
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.trade.controller

